### PR TITLE
frontend: revamp message component and replace inlinemessage

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by thisconnect** [comment]
Screenshot 2024-06-20 at 11 49 20
Screenshot 2024-06-20 at 11 49 29

**Comment by thisconnect** [comment]
Screenshot 2024-06-20 at 10 48 05
Screenshot 2024-06-20 at 11 00 46
Screenshot 2024-06-20 at 11 43 17

**Comment by thisconnect** [comment]
Screenshot 2024-06-20 at 11 42 08
Screenshot 2024-06-20 at 11 42 31
Screenshot 2024-06-20 at 11 42 48

**Comment by thisconnect** [comment]
cc @shonsirsha @jadzeidan

**Comment by jadzeidan** [comment]
Very nice :)

**Review by shonsirsha — APPROVED** [review]
LGTM. Tested on macOS webdev. One thing I noticed is this weird (insufficient) spacing between the warning message and the radio button.

asxsax


But I can't seem to see it in your screenshot @thisconnect

**Comment by thisconnect** [comment]
Thanks for catching, I'll open a separate PR for this. Probably together with https://github.com/thisconnect/bitbox-wallet-app/commits/frontend-label-styling/

**Comment by thisconnect** [comment]
@shonsirsha spacing is similar/same as before, see

Screenshot 2024-06-25 at 11 26 37

but the radio buttons are not vertically aligned with labels, this should be fixed in  https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/2779

**Pull request merged**
