### PR TITLE
frontend/android: remove unused CONNECTED_DEVICE permission

### PR DESCRIPTION
**Pull request by Beerosagos**

### CODE REVIEW

**Comment by Beerosagos** [comment]
Converted to draft as I want to do one more change

**Comment by Beerosagos** [comment]
ping @benma, when you have time :innocent:

**Review by benma — APPROVED** [review]
The commit message could have more info, it's missing the 'why' :nerd_face: But LGTM

**Comment by Beerosagos** [comment]
> The commit message could have more info, it's missing the 'why' 🤓 But LGTM

Well, it says it is unused :D Anyway, I added some details

**Pull request merged**
