### PR TITLE
frontend: bump react/react-dom version to 18.3.1

### PR DESCRIPTION
**Pull request by NicolaLS**
~~after: #2750~~

Squashed react-dom and react update into one commit.

tested on `webdev` firefox, software keystore.

all peerDependencies support at lest `^18.0.0`

```
[sus@archlinux web]$ npm ls react-dom
bitboxapp@0.0.0 /home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web
├─┬ @testing-library/react@14.3.1
│ └── react-dom@18.3.1 deduped
├── react-dom@18.3.1
├─┬ react-router-dom@6.4.3
│ └── react-dom@18.3.1 deduped
└─┬ react-select@5.8.0
  ├── react-dom@18.3.1 deduped
  └─┬ react-transition-group@4.4.5
    └── react-dom@18.3.1 deduped

[sus@archlinux web]$ cat ./node_modules/react-select/package.json | grep peerDependencies -A 5
  "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
  },
  "files": [
    "dist",
[sus@archlinux web]$ cat ./node_modules/react-router-dom/package.json | grep peerDependencies -A 5
  "peerDependencies": {
    "react": ">=16.8",
    "react-dom": ">=16.8"
  },
  "files": [
    "dist/",
[sus@archlinux web]$ cat ./node_modules/@testing-library/package.json | grep peerDependencies -A 5
cat: ./node_modules/@testing-library/package.json: No such file or directory
[sus@archlinux web]$ cat ./node_modules/@testing-library/react/package.json | grep peerDependencies -A 5
  "peerDependencies": {
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  },
  "eslintConfig": {
    "extends": "./node_modules/kcd-scripts/eslint.js",
[sus@archlinux web]$

```

### CODE REVIEW

**Comment by NicolaLS** [comment]
@thisconnect this PR now updates react and react-dom in the same commit.

**Comment by thisconnect** [comment]
I checked https://github.com/facebook/react/blob/main/CHANGELOG.md

Looks like they mostly added deprecation warnings for upcoming react 19.

One appears now in `make webtest` could you fix this?

> stderr | src/hooks/api.test.ts > hooks for api calls > useLoad > re-calls apiCall when dependencies change
Warning: `ReactDOMTestUtils.act` is deprecated in favor of `React.act`. Import `act` from `react` instead of `react-dom/test-utils`. See https://react.dev/warnings/react-dom-test-utils for more info.

**Comment by thisconnect** [comment]
sorry i just realized, please update this together with @types/react in this PR

**Comment by NicolaLS** [comment]
> sorry i just realized, please update this together with @types/react in this PR

makes sense :) updating `@types/react` to 18.3.3` creates a ts error:

```
7:47:34 AM [vite] Internal server error:
/home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/src/routes/account/send/send.tsx
  55:5  error  'transaction' PropType is defined but prop is never used  react/no-unused-prop-types

✖ 1 problem (1 error, 0 warnings)

  Plugin: vite-plugin-eslint
  File: /home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/src/routes/account/send/send.tsx
      at formatError (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52009:46)
      at TransformContext.error (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52003:19)
      at TransformContext.transform (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite-plugin-eslint/dist/index.mjs:1:1989)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transform (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:52318:30)
      at async loadAndTransform (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:55073:29)
      at async viteTransformMiddleware (file:///home/sus/Work/bitbox/dev/bitbox-wallet-app/frontends/web/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:64920:32)
```

I'll fix it in another commit.

**Comment by NicolaLS** [comment]
@thisconnect updated `@types/react` to `18.3.3` did some testing on `webdev` firefox software keystore everything seems to be fine.

**Comment by NicolaLS** [comment]
> @thisconnect updated `@types/react` to `18.3.3` did some testing on `webdev` firefox software keystore everything seems to be fine.

did not see the comment about the deprecation warning initially. is fixed now, I also updated `@types/react-dom` to `18.3.0`

**Review by thisconnect — APPROVED** [review]
tested LGTM

**Pull request merged**
