### PR TITLE
Frontend fix css regression

### PR DESCRIPTION
**Pull request by thisconnect**

### CODE REVIEW

**Comment by NicolaLS** [comment]
tested `AppImage` LGTM! 
- Sidebar scroll works
- Pocket and Moonpay show properly now

**Comment by thisconnect** [comment]
added a commit that should fix:
- height not expanding to full height when the content is smaller than the window height
- dialogs always using full height

what to test:
- waiting view
- dialog i.e. enable tor proxy
- bootloader view (using centeredcontent comp)

**Comment by NicolaLS** [comment]
tested `webdev` firefox (BB02B and software keystore), `AppImage` on linux and the android app. the problem with the dialog expanding is fixed, not sure what the issue with bootloader view and waiting view was but they looked normal to me too.

**Comment by shonsirsha** [comment]
Tested on Chrome webdev macOS. Seems to fix the regressions. 👍 


blv

mb

bbtc

tp

password

**Review by shonsirsha — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
